#!/bin/bash

##############################
### Link dotfiles to $HOME ###
##############################

### this is a function that links a dotfile to $HOME directory
link_file() {
	local file=$1
	if [[ -f ~/dotfiles/${file} ]]; then
		ln -sf ~/dotfiles/"${file}" ~/"${file}"
		echo "\"""$file""\" linked"
	fi
}

### this is an array with a list of dotfiles to be linked to $HOME directory
dotfile_list=(".bashrc" ".tmux.conf" ".vimrc")

# linking the dotfiles
for dotfile in "${dotfile_list[@]}"; do
	link_file "${dotfile}"
done
#### END link dotfiles section ####


#############################
####     Setup $PATH     ####
### for personal bineries ###
#############################

if [[ ! -d ~/.local/bin ]]; then
	mkdir -p ~/.local/bin
	echo "$HOME/.local/bin created"
	echo 'export PATH="$HOME/.local/bin:$PATH"' >> ~/.bashrc
fi
#### END $PATH section ####


echo "Done!"
