#!/bin/bash

### this is a function that links a dotfile to $HOME directory 
link_file() {
	local file=$1
	if [[ -f ~/dotfiles/${file} ]]; then
		ln -sf ~/dotfiles/"${file}" ~/"${file}"
		echo "\"""$file""\" linked"
	fi
}

### this is an array with a list of dotfiles to be linked to $HOME directory
dotfile_list=(".bashrc" ".tmux.conf")

# linking the dotfiles
for dotfile in "${dotfile_list[@]}"; do
	link_file "${dotfile}"
done

echo "Done!"
